name: MyWhiteSpots
favicon: null
layout_spectrum: 0.05877
typography_spectrum: 0.2653652986045927
title: MyWhiteSpots
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#736458'
    - '#ffffff'
    - '#3e362b'
    - '#a1978e'
    - '#005a6d'
  brandStrength: 0.28417509770952165
  lightness: 0.5576539123430848
  saturation: 0.4662988029886037
  rhythmicContrast: 0.4222437897697091
purpose: []
